name: Unit Tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # May need pinning at some point!
      - name: Install Tox
        run: pip install tox

      - name: Run tests using Tox
        run: tox
